-- Migration 009: Seed current marketing data for head verification
-- Requires migration 008 (MIS columns). Idempotent via the 'seed-mis' tag.
-- Assigned by Anuja Mulik (Marketing head). Emails assumed @hscvpl.com.

DO $$
DECLARE k_id uuid; s_id uuid; b_id uuid;
BEGIN
  SELECT id INTO k_id FROM auth.users WHERE email='krishnendu.br@hscvpl.com';
  SELECT id INTO s_id FROM auth.users WHERE email='suresh.swanti@hscvpl.com';
  SELECT id INTO b_id FROM auth.users WHERE email='bhavesh.ambekar@hscvpl.com';

  -- Krishnendu BR (designer-mis)
  IF k_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tasks WHERE user_id=k_id AND 'seed-mis'=ANY(tags)) THEN
    INSERT INTO public.tasks (title, task_giver, user_id, user_email, assigned_to_email, team_name, status, priority, recurrence, position, tags, created_at, mis_role, channel, task_type, num_products, num_creatives, total_designs, approved_input, rejected_inputs, quality_score, start_date, deadline, actual_delivery) VALUES
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,42,5,1,0,5,'2026-01-10','2026-01-10','2026-01-10'),
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,56,8,1,0,5,'2026-02-10','2026-02-10','2026-02-10'),
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,49,7,1,0,5,'2026-03-10','2026-03-10','2026-03-10'),
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,42,6,1,0,5,'2026-04-10','2026-04-10','2026-04-10'),
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,42,6,1,0,5,'2026-05-10','2026-05-10','2026-05-10'),
    ('Ecom Flipkart PDP','Anuja Mulik',k_id,'krishnendu.br@hscvpl.com','krishnendu.br@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,35,5,1,0,5,'2026-06-10','2026-06-10','2026-06-10');
    RAISE NOTICE 'Seeded 6 rows for Krishnendu BR';
  END IF;

  -- Suresh Swanti (designer)
  IF s_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tasks WHERE user_id=s_id AND 'seed-mis'=ANY(tags)) THEN
    INSERT INTO public.tasks (title, task_giver, user_id, user_email, assigned_to_email, team_name, status, priority, recurrence, position, tags, created_at, mis_role, channel, task_type, num_products, num_creatives, total_designs, approved_input, rejected_inputs, quality_score, start_date, deadline, actual_delivery) VALUES
    ('Ecom Mynta PDP','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,21,NULL,NULL,NULL,NULL,'2026-01-06',NULL,NULL),
    ('Ecom Mynta PDP','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,21,NULL,NULL,NULL,NULL,'2026-02-06',NULL,NULL),
    ('Ecom Mynta PDP','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,56,NULL,NULL,NULL,NULL,'2026-03-06',NULL,NULL),
    ('Ecom Mynta PDP','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',NULL,21,NULL,NULL,NULL,NULL,'2026-04-06',NULL,NULL),
    ('MT Reliance Box packaging Magnum','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',1,4,NULL,NULL,NULL,NULL,'2026-05-06',NULL,NULL),
    ('MT Reliance Box packaging Solo','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer','Online','PDP''s / A+ Content',1,4,NULL,NULL,NULL,NULL,'2026-06-06',NULL,NULL),
    ('MT Reliance Box packaging Magnum','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,'Box/ Carton Design',1,10,NULL,NULL,NULL,NULL,'2026-08-06',NULL,NULL),
    ('MT Reliance Box packaging Solo / Linked post','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,'Box/ Carton Design',1,5,NULL,NULL,NULL,NULL,'2026-09-06',NULL,NULL),
    ('Institutional whatsapp creative (Leave 2nd half)','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,'Social Media Creative',NULL,2,NULL,NULL,NULL,NULL,'2026-10-06',NULL,NULL),
    ('Institutional whatsapp creative','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'2026-11-06',NULL,NULL),
    ('Sticker Luggage Bag / Magnum/Solo box packaging','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,NULL,NULL,9,NULL,NULL,NULL,NULL,'2026-12-06',NULL,NULL),
    ('Dufle cosmos box packaging','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,NULL,1,8,NULL,NULL,NULL,NULL,'2026-06-15',NULL,NULL),
    ('Dufle cosmos box packaging','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,NULL,1,6,NULL,NULL,NULL,NULL,'2026-06-16',NULL,NULL),
    ('PDP Icon &  MT Reliance Box packaging Solo','Anuja Mulik',s_id,'suresh.swanti@hscvpl.com','suresh.swanti@hscvpl.com','Marketing','pending','medium','none',0,ARRAY['seed-mis'],now(),'designer',NULL,NULL,NULL,18,NULL,NULL,NULL,NULL,'2026-06-17',NULL,NULL);
    RAISE NOTICE 'Seeded 14 rows for Suresh Swanti';
  END IF;

  -- Bhavesh Ambekar (regular)
  IF b_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tasks WHERE user_id=b_id AND 'seed-mis'=ANY(tags)) THEN
    INSERT INTO public.tasks (title, task_giver, user_id, user_email, assigned_to_email, team_name, status, priority, recurrence, position, tags, created_at, mis_role, channel, task_type, num_products, num_creatives, total_designs, approved_input, rejected_inputs, quality_score, start_date, deadline, actual_delivery) VALUES
    ('Monthly review tasks','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-06',NULL,NULL),
    ('Comment on RCB and Virat Kohli''s Instagram post, then share the "priority bags" comment along with RCB''s post to our IG story.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-06',NULL,NULL),
    ('Make monthly Content calendar presentation','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-06',NULL,NULL),
    ('Social media calender references and ideas','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-06',NULL,NULL),
    ('Create a Pinterest business account for Priority Bags using the marketing email ID.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-06',NULL,NULL),
    ('Monitor Instagram story metrics and download May Insights from Business Suite to analyze growth trends','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-06',NULL,NULL),
    ('Meeting for discussing Instagram post references and ideas','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-06',NULL,NULL),
    ('Story highlights Section Discussion','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-06',NULL,NULL),
    ('References for social media posting and deciding with sequence','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-06',NULL,NULL),
    ('Revise selected posts in the content plan and source appropriate references for the respective products.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-06',NULL,NULL),
    ('Segregate content buckets, assign owners in the calendar, and email the team regarding their upcoming content creation and creative tasks..','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-06',NULL,NULL),
    ('FIFA World Cup brainstorming ideas and trend posts','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-05-06',NULL,NULL),
    ('Post the collaborative reel of an influencer by Ajiogram to Priority Bags'' IG and Facebook stories','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-05-06',NULL,NULL),
    ('Co-ordinate with Graphic designers and video editor for the upcoming creatives and reels.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-05-06',NULL,NULL),
    ('Make video with photographer and scripted feature videos for the football themed bags','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-09-06',NULL,NULL),
    ('Co-ordinate with the web developer to create a unified QR code linking all social media handles to print on the gift boxes.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-09-06',NULL,NULL),
    ('Brainstorm references, write the caption, co-ordinate with the graphic designer on the creative, and publish the Chennai office LinkedIn post by EOD.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-09-06',NULL,NULL),
    ('Promote the chennai office Linkedin Post on Whatsapp and verbally','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-10-06',NULL,NULL),
    ('Work on Monthly content plan for LinkedIn','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-10-06',NULL,NULL),
    ('Publish the FIFA world cup reel on Meta Platforms','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-10-06',NULL,NULL),
    ('Work on Monthly content Plan for LinkedIn','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-11-06',NULL,NULL),
    ('Immediately work on the USA Shipment post and it''s caption for LinkedIn','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-11-06',NULL,NULL),
    ('Co-ordinate with video editor for the USA Shipment post','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-12-06',NULL,NULL),
    ('Work on Monthly content Plan for LinkedIn','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-12-06',NULL,NULL),
    ('Co-ordinate with designer and make FIFA creative carousel post for Meta Platforms','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-15',NULL,NULL),
    ('Co-ordinate with video editor and make changes in the Likedin video for USA Shipment','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-15',NULL,NULL),
    ('Publish USA shipment video on LinkedIn & promote it in the whatsapp groups','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-16',NULL,NULL),
    ('Publish Fifa Carousel on Meta Platforms by EOD','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-16',NULL,NULL),
    ('Re-referencing for upcoming LinkedIn & Meta posts','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-16',NULL,NULL),
    ('Present the LinkedIn plan and start working on the posts and caption','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-17',NULL,NULL),
    ('Publish Fifa Carousel on Pinterest to create our presence and awareness.','Anuja Mulik',b_id,'bhavesh.ambekar@hscvpl.com','bhavesh.ambekar@hscvpl.com','Marketing','completed','medium','none',0,ARRAY['seed-mis'],now(),'none',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-17',NULL,NULL);
    RAISE NOTICE 'Seeded 31 rows for Bhavesh Ambekar';
  END IF;

END $$;